load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


# git_repository(
#     name = "com_google_absl",
#     remote = "https://gitee.com/zqx5449/abseil-cpp.git",
#     tag = "20230125.1",
# )

git_repository(
    name = "com_google_googletest",
    remote = "https://gitee.com/zqx5449/googletest.git",
    tag = "v1.13.0",
)

git_repository(
    name = "com_google_protobuf",
    remote = "https://gitee.com/zqx5449/protobuf.git",
    tag = "v3.22.0",
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()