load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# git_repository(
#     name = "bazel_toolchains",
#     remote = "https://github.com/bazelbuild/bazel-toolchains.git",
#     tag = "v5.1.2",
# )
# load("@bazel_toolchains//repositories:repositories.bzl", bazel_toolchains_repositories = "repositories")
# bazel_toolchains_repositories()

git_repository(
    name = "com_github_grpc_grpc",
    remote = "https://github.com/grpc/grpc.git",
    tag = "v1.51.3",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()


git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.24.0",
)


load("@io_bazel_rules_docker//repositories:repositories.bzl",container_repositories = "repositories",)
container_repositories()

load("@io_bazel_rules_docker//container:pull.bzl", "container_pull")

container_pull(
  name = "official_ubuntu",
    registry = "index.docker.io",
    repository = "library/ubuntu",
    tag = "14.04",
)

# load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
# container_deps()

# load("@io_bazel_rules_docker//cc:image.bzl", _cc_image_repos = "repositories",)
# _cc_image_repos()