apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellosvr
  name: hellosvr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellosvr
  template:
    metadata:
      labels:
        app: hellosvr
    spec:
      containers:
      - name: hellosvr
        image: ccr.ccs.tencentyun.com/hmjmf/hellosvr_server:latest
        ports:
        - containerPort: 30000
        env:
        - name: respmsg
          valueFrom:
            configMapKeyRef:
              name: hellosvr-config
              key: respmsg
        - name: port
          valueFrom:
            configMapKeyRef:
              name: hellosvr-config
              key: port